# Read the Docs configuration file (Japanese translation project)
#
# RTD translations already prefix URLs with the language (/en/latest/, /ja/latest/).
# This config therefore builds docs/ja/** as the documentation ROOT so pages are:
#   /ja/latest/index.html
# (no duplicated /ja/ path segment).
#
# In the Read the Docs project settings for the Japanese project, set
# "Build configuration file" to:
#   .readthedocs/ja/.readthedocs.yaml
#
# See https://docs.readthedocs.com/platform/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - pip install uv
    post_install:
      - uv pip install -e ".[docs]"

sphinx:
  configuration: docs/ja/conf.py
  fail_on_warning: false

formats:
  - pdf
  - epub
